### PR TITLE
POAP Web APP basic setup

### PR DESCRIPTION
**Pull request by TusharPardhe**
How to run?
- Download the github repository
- Navigate to the repository and open terminal
- In terminal type `yarn` or `npm i`
- After installation of all packages, edit the .env file
- Type `yarn dev` or `npm run dev` to run the web app

Screenshots for Mint NFT Feature: 

Screenshot 2023-06-10 at 12 19 33 am
Screenshot 2023-06-10 at 12 19 52 am
Screenshot 2023-06-10 at 12 20 40 am
Screenshot 2023-06-10 at 12 20 48 am

I will start working on other features after approaval on the design :)

### CODE REVIEW

**Comment by JST5000** [comment]
I'm not quite sure what I'm doing wrong - when I follow the instructions I can get to a screen that prompts for a sign-in: 
image


But then when click `sign in with Xumm` I get an error page - 
image

And the GemWallet button doesn't seem to do anything when I click it unfortunately.

**Comment by JST5000** [comment]
(I created my own API key with Xumm, and included it, but it doesn't change whether I have that key in the `.env` file or not)

**Comment by TusharPardhe** [comment]
> (I created my own API key with Xumm, and included it, but it doesn't change whether I have that key in the `.env` file or not)

In the XUMM APP Dev dashboard there's a field in the bottom "redirection URL". In that we've to add our app url for eg: "localhost:5000" (Apologies should've included this in the points)

**Comment by TusharPardhe** [comment]
> I'm not quite sure what I'm doing wrong - when I follow the instructions I can get to a screen that prompts for a sign-in: image
> 
> But then when click `sign in with Xumm` I get an error page - image
> 
> And the GemWallet button doesn't seem to do anything when I click it unfortunately.

You can just navigate to /dashboard 

Login is just for the testing purpose (After Gemwallet signin your wallet address will be in console meaning success). I did that cause will have to maintain a separate mongoDB server for that as mentioned in a point as well, separating event attendes and creators

**Comment by jonathanlei** [comment]
Could you add a README explaining the architecture and include the running instructions?

**Comment by JST5000** [comment]
> In the XUMM APP Dev dashboard there's a field in the bottom "redirection URL". In that we've to add our app url for eg: "localhost:5000" (Apologies should've included this in the points)

When I search for `redirection URL` I can't find any field like that in your repo. Could you maybe add instructions with screenshots to help me figure out how to get that side working? 

As for GemWallet - when I click that I don't see anything in the console, maybe those changes haven't been pushed yet? (I double checked that I git pulled beforehand)

Screenshot of what I see after clicking Xumm and then GemWallet buttons. 
image

**Comment by TusharPardhe** [comment]
I will update the readme as soon as possible, till then please look at these videos to get a general idea of the APP

Video links for the pages @JST5000 @JST5000 
Login: https://youtu.be/06Woj2gqk4Y
Dashboard: https://youtu.be/rQUnRmruWmI

**Comment by JST5000** [comment]
> Video links for the pages @JST5000 @JST5000

Ah, thanks for the videos! Watching now :) 

(And already realize that I wasn't seeing anything from Gem because I don't believe I have the extension installed and so I think it was erroring out silently. Could you add a louder error for if that's the case?)

**Comment by TusharPardhe** [comment]
> > Video links for the pages @JST5000 @JST5000
> 
> Ah, thanks for the videos! Watching now :)
> 
> (And already realize that I wasn't seeing anything from Gem because I don't believe I have the extension installed and so I think it was erroring out silently. Could you add a louder error for if that's the case?)

Yeah I will add

**Comment by JST5000** [comment]
1. Once a user logs in, can we auto-populate the `Wallet Address` field for Mint NFTs? (It's hard to copy from my phone the exact address of my account otherwise)
2. When I go to mint after logging in with Xumm, I run into an "uncaught type error" (screenshot below) - any idea why that might be?
image

Full screen
image

**Comment by TusharPardhe** [comment]
> 1. Once a user logs in, can we auto-populate the `Wallet Address` field for Mint NFTs? (It's hard to copy from my phone the exact address of my account otherwise)
> 
> 2. When I go to mint after logging in with Xumm, I run into an "uncaught type error" (screenshot below) - any idea why that might be?
> 
> image
> 
> 
> 
> Full screen
> 
> image
> 
> 
> 
> 

1. Yes I'll implement it.

2. In POAP Back end CORS is not enabled, I had to add it in, I believe I created a new branch adding cors

**Pull request closed without merging**
